'use client'

import {
  CheckCircle2,
  LoaderCircle,
  QrCode,
  X,
} from 'lucide-react'
import {
  useEffect,
  useState,
  type FormEvent,
} from 'react'
import {
  getOrderReference,
  getOrderStatus,
  getOrderUserName,
} from '@/lib/order'
import {
  toApiDateTime,
  toDateTimeLocal,
} from '@/lib/order-qr-code'
import type { Order } from '@/types/order'
import type {
  OrderQrCode,
  OrderQrCodePayload,
} from '@/types/order-qr-code'

interface OrderQrCodeFormModalProps {
  isOpen: boolean
  qrCode?: OrderQrCode | null
  orders: Order[]
  isLoadingOrders: boolean
  isSubmitting: boolean
  onClose: () => void
  onSubmit: (
    payload: OrderQrCodePayload,
  ) => Promise<void>
}

export default function OrderQrCodeFormModal({
  isOpen,
  qrCode,
  orders,
  isLoadingOrders,
  isSubmitting,
  onClose,
  onSubmit,
}: OrderQrCodeFormModalProps) {
  const [orderId, setOrderId] = useState('')
  const [expiresAt, setExpiresAt] =
    useState('')
  const [notes, setNotes] = useState('')
  const [formError, setFormError] =
    useState('')

  const editing = Boolean(qrCode)

  useEffect(() => {
    if (!isOpen) {
      return
    }

    setOrderId(
      qrCode?.order_id === undefined ||
        qrCode?.order_id === null
        ? ''
        : String(qrCode.order_id),
    )

    setExpiresAt(
      toDateTimeLocal(qrCode?.expires_at),
    )

    setNotes(qrCode?.notes ?? '')
    setFormError('')
  }, [isOpen, qrCode])

  async function handleSubmit(
    event: FormEvent<HTMLFormElement>,
  ) {
    event.preventDefault()
    setFormError('')

    if (!orderId) {
      setFormError(
        'Please select an order.',
      )
      return
    }

    if (
      expiresAt &&
      new Date(expiresAt).getTime() <= Date.now()
    ) {
      setFormError(
        'The expiration date must be in the future.',
      )
      return
    }

    try {
      await onSubmit({
        order_id: orderId,
        expires_at: toApiDateTime(expiresAt),
        notes: notes.trim(),
      })
    } catch (error) {
      setFormError(
        error instanceof Error
          ? error.message
          : 'Unable to save the QR code.',
      )
    }
  }

  if (!isOpen) {
    return null
  }

  const selectableOrders = orders.filter(
    (order) => {
      const status = getOrderStatus(order)

      return (
        !order.deleted_at &&
        status !== 'cancelled'
      )
    },
  )

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <button
        type="button"
        aria-label="Close QR code form"
        onClick={onClose}
        disabled={isSubmitting}
        className="absolute inset-0 bg-slate-950/50 backdrop-blur-sm"
      />

      <div className="relative z-10 w-full max-w-xl overflow-hidden rounded-3xl bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-slate-200 px-6 py-5">
          <div className="flex items-center gap-3">
            <span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-600">
              <QrCode className="h-5 w-5" />
            </span>

            <div>
              <h2 className="font-extrabold text-slate-950">
                {editing
                  ? 'Update Order QR Code'
                  : 'Create Order QR Code'}
              </h2>

              <p className="text-xs text-slate-500">
                The secure QR token is generated by Laravel.
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            disabled={isSubmitting}
            className="rounded-xl p-2 text-slate-400 hover:bg-slate-100"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <form
          onSubmit={handleSubmit}
          className="space-y-5 p-6"
        >
          {formError && (
            <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
              {formError}
            </div>
          )}

          <div>
            <label
              htmlFor="qr-order"
              className="mb-2 block text-sm font-bold text-slate-700"
            >
              Order
            </label>

            {isLoadingOrders ? (
              <div className="flex h-12 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-500">
                <LoaderCircle className="h-4 w-4 animate-spin text-indigo-600" />
                Loading orders...
              </div>
            ) : (
              <select
                id="qr-order"
                value={orderId}
                onChange={(event) =>
                  setOrderId(event.target.value)
                }
                required
                disabled={
                  isSubmitting || editing
                }
                className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-100 disabled:opacity-60"
              >
                <option value="">
                  Select order
                </option>

                {selectableOrders.map(
                  (order) => (
                    <option
                      key={order.id}
                      value={String(order.id)}
                    >
                      {getOrderReference(order)}
                      {' — '}
                      {getOrderUserName(order)}
                    </option>
                  ),
                )}
              </select>
            )}

            {editing && (
              <p className="mt-2 text-xs text-slate-400">
                The order cannot be changed after QR
                creation.
              </p>
            )}
          </div>

          <div>
            <label
              htmlFor="qr-expires-at"
              className="mb-2 block text-sm font-bold text-slate-700"
            >
              Expiration date and time
            </label>

            <input
              id="qr-expires-at"
              type="datetime-local"
              value={expiresAt}
              onChange={(event) =>
                setExpiresAt(event.target.value)
              }
              disabled={isSubmitting}
              className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-100"
            />

            <p className="mt-2 text-xs text-slate-400">
              Leave empty only when the backend supports
              its own default expiry.
            </p>
          </div>

          <div>
            <label
              htmlFor="qr-notes"
              className="mb-2 block text-sm font-bold text-slate-700"
            >
              Notes
            </label>

            <textarea
              id="qr-notes"
              value={notes}
              onChange={(event) =>
                setNotes(event.target.value)
              }
              rows={4}
              disabled={isSubmitting}
              placeholder="Optional information about this QR code..."
              className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-100"
            />
          </div>

          <div className="flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="h-11 rounded-xl border border-slate-200 px-5 text-sm font-bold text-slate-600"
            >
              Cancel
            </button>

            <button
              type="submit"
              disabled={
                isSubmitting ||
                isLoadingOrders ||
                !orderId
              }
              className="flex h-11 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 text-sm font-bold text-white hover:bg-indigo-700 disabled:opacity-50"
            >
              {isSubmitting ? (
                <>
                  <LoaderCircle className="h-4 w-4 animate-spin" />
                  Saving...
                </>
              ) : (
                <>
                  <CheckCircle2 className="h-4 w-4" />
                  {editing
                    ? 'Update QR Code'
                    : 'Create QR Code'}
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
